config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  post 'users/user_branch/:id', to: 'users#user_branch', as: 'user_branch'
  put 'branch_products/update_branch_products_list/:id', to: 'branch_products#update_branch_products_list', as: 'branch_products_update'
  put 'branch_inventories/update_branch_inventory_items_list/:id', to: 'branch_inventories#update_branch_inventory_items_list', as: 'branch_inventory_update'
  put 'branch_premade_items/update_branch_premade_items_list/:id', to: 'branch_premade_items#update_branch_premade_items_list', as: 'branch_premade_items_update'
  
  # edit and update product's inventory item and premade item
  post 'products/edit_product_inventory_item/:id', to: 'products#edit_product_inventory_item', as: 'edit_product_item'
  put 'products/update_product_inventory_item/:id', to: 'products#update_product_inventory_item', as: 'update_product_item'
  post 'products/edit_product_premade_item/:id', to: 'products#edit_product_premade_item', as: 'edit_product_premade_item'
  put 'products/update_product_premade_item/:id', to: 'products#update_product_premade_item', as: 'update_product_premade_item'
  
  post 'premade_items/edit_premade_inventory_item/:id', to: 'premade_items#edit_premade_inventory_item', as: 'edit_premade_inventory_item'
  put 'premade_items/update_premade_inventory_item/:id', to: 'premade_items#update_premade_inventory_item', as: 'update_premade_inventory_item'

  post 'branch_inventories/edit_individual_branch_inventory_items', to: 'branch_inventories#edit_individual_branch_inventory_items', as: 'edit_individual_branch_inventory_items'
  put 'branch_inventories/update_individual_branch_inventory_items', to: 'branch_inventories#update_individual_branch_inventory_items', as: 'update_individual_branch_inventory_items'
  
  post 'branch_premade_items/edit_individual_branch_premade_items', to: 'branch_premade_items#edit_individual_branch_premade_items', as: 'edit_individual_branch_premade_items'
  put 'branch_premade_items/update_individual_branch_premade_items', to: 'branch_premade_items#update_individual_branch_premade_items', as: 'update_individual_branch_premade_items'
  
  get 'home/unit_chart', as: 'unit_chart'
  get 'transfers/selected_item_unit/:id', to: 'transfers#selected_item_unit'

  resources :products, :inventory_items, :premade_items, :transfers
  resources :branch_products, :branch_inventories, :branch_premade_items, only: [ :index, :edit, :update ]
end

app/models/premade_item.rb
class PremadeItem < ApplicationRecord
  validates_presence_of :name, :unit, :item_type, :item_quantity, on: [ :create, :update ]
  validates_uniqueness_of :name, on: [ :create, :update ]
  
  has_many :branch_premade_items, dependent: :destroy
  has_many :branches, through: :branch_premade_items
  
  has_many :premade_inventory_items, dependent: :destroy
  has_many :inventory_items, through: :premade_inventory_items
  
  has_many :product_premade_items, dependent: :destroy
  has_many :products, through: :product_premade_items

  before_validation do | item |
    item.name = item.name.downcase.capitalize
    item.unit = item.unit.downcase.singularize
  end
end

app/controllers/premade_items_controller.rb
class PremadeItemsController < ApplicationController
  def index
    @list = params[ :list ]
    @premade_items = PremadeItem.all
  end

  def new
    @item = PremadeItem.new
    @inventory_items = InventoryItem.all
    @units = helpers.units.keys
    @types = PremadeItem.all.pluck( :item_type ).uniq
  end

  def create
    item = PremadeItem.new( item_params )

    if item.save
      redirect_back( fallback_location: premade_items_path, notice: "#{ item.name } has been successfully added" )
    else
      redirect_back( fallback_location: premade_items_path, notice: 'failed to save new item' )
    end
  end

  def edit
    @item = PremadeItem.find( params[ :id ] )
    @inventory_items = InventoryItem.all
    @valid_units = helpers.find_valid_item_units( @item )
    @types = PremadeItem.all.pluck( :item_type ).uniq
  end

  def update
    item = PremadeItem.find( params[ :id ] )

    if item.update( item_params )
      redirect_to premade_item_path( item ), method: 'get', notice: "edit successful"
    else
      redirect_back( fallback_location: premade_items_path, notice: 'edit failed' )
    end
  end

  def show
    @premade_item = PremadeItem.find( params[ :id ] )
    @premade_inventory_items = PremadeInventoryItem.where( premade_item_id: @premade_item.id )
    @complete_item = params[ :complete_item ]
  end

  def destroy
    item = PremadeItem.find( params[ :id ] )

    deny_joined_objects_with_premade( item )
    
    if item.destroy
      redirect_to premade_items_path, method: 'get', notice: "#{ item.name } has been deleted"
    else
      redirect_back( fallback_location: premade_items_path, notice: 'delete failed' )
    end
  end

  def edit_premade_inventory_item
    @premade_inventory_item = PremadeInventoryItem.find( params[ :id ] )
    
    @valid_units = helpers.find_valid_item_units( @premade_inventory_item )
  end
  
  def update_premade_inventory_item
    premade_item = PremadeInventoryItem.find( params[ :id ] )

    if premade_item.update( premade_item_params )
      redirect_to premade_item_path( premade_item.premade_item, focus: true ), method: 'get', notice: 'edit successful'
    else
      redirect_to premade_items_path, method: 'get', notice: "edit failed"
    end
  end

  private

  def item_params
    params.require( :premade_item ).permit( :name, :unit, :item_quantity, :item_type, :vouched, inventory_item_ids: [] )
  end

  def premade_item_params
    params.require( :premade_inventory_item ).permit( :unit, :unit_count )
  end

  def deny_joined_objects_with_premade( item )
    products = Product.includes( :premade_items ).where( premade_items: { id: item.id } )

    products.update_all( vouched: false ) unless products.nil?
  end
end

app/helpers/costings/premade_item.rb
module Costings::PremadeItem
  
  # returns the collective cost of joined inventory items
  def accumulated_cost_of( joins, cost = 0 )
    
    joins.each do | join |
      item_cost = item_cost( join )
      
      cost += item_cost
    end
    cost
  end
  
  def premade_item_cost( premade_item )
    return nil unless verified_and_complete?( premade_item )
    
    inventory_item_joins = PremadeInventoryItem.where( premade_item: premade_item )

    accumulated_cost_of( inventory_item_joins )
  end
end

app/helpers/premade_items_helper.rb
module PremadeItemsHelper
end

app/helpers/validators/premade_item.rb
module Validators::PremadeItem

  def no_null_data_is_detected_from?( model_joins )
    model_joins.where( unit_count: nil ).count == 0
  end
  
  def premade_item_has_no?( inventory_items )
    inventory_items.count.zero?
  end
  
  def complete_premade_item_data_values?( premade_item )
    premade_inventory_items = PremadeInventoryItem.where( premade_item: premade_item )

    return false if premade_item_has_no?( premade_inventory_items ) ||
                    null_data_is_detected_from?( premade_inventory_items )

    true
  end
end

app/views/premade_items/_table.html.erb
<table class = 'table'>

  <caption id='caption'>
    Premade Items
    <hr>
  </caption>
  
  <thead>
    <tr>
      <th>
        Item
        <%= link_to '[ ' "\u{ 002B }" ' ]'.encode( 'utf-8' ), new_premade_item_path, method: 'get' %>
      </th>

      <th>Quantity</th>
      
      <th>Cost</th>
    </tr>
  </thead>
  
  <% @premade_items.each do | premade_item | %>
    
    <tbody>
      <tr>
        <td>
          <%# go to 'show_view': premade item's composition( inventory items ) %>
          <%= link_to premade_item.name,
              premade_item_path( premade_item, complete_item: complete_premade_item_data_values?( premade_item ) ),
              class: compliance_class_of( premade_item ),
              method: 'get' %>
        </td>

        <td>
          <%= unit_quantity_of( premade_item, true ) %>
        </td>

        <td>
          <%= cost_of( premade_item ) %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

<%# table for premade items with accumulated costs from it's composition( inventory_items ) %>

app/views/premade_items/edit.html.erb
<%= link_to parent_view, premade_items_path, method: 'get', class: 'return-link' %>
<%= 'premade items' %>

<h3 style="text-align: center;">
  Premade Item( <%= @item.name %> )
  <%= link_to '[x]', premade_item_path( @item ), method: 'delete', data: { confirm: 'Are you sure you want to delete this item?' } %>
</h3><br>

<%= simple_form_for @item do |f| %>
  <p>
    <%= f.label 'Name*' %>
    <%= f.input :name, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Unit*" %>
    <%= link_to list_unicode, unit_chart_path, method: 'get' %>
    <div class="input-group">
      <%= f.input :item_quantity, label: false, input_html: { class: 'form-control', placeholder: 'quantity' } %>

      <span class="input-group-addon"> &nbsp &nbsp</span>
      
      <%= f.input :unit, as: :select, collection: @valid_units, label: false, input_html: { class: 'form-control', placeholder: 'item unit' } %> 
    </div>
  </p>
  
  <p>
    <%= f.label 'Type*' %>
    <%= f.input :item_type, label: false, input_html: { type: 'text', list: 'types', autocomplete: 'off', class: 'form-control' } %>
    <datalist id="types">
      <% @types.each do | type | %>
        <option><%= type %></option>
      <% end %>
    </datalist>
  </p><br>

  <p>
    <%= f.label "Components:" %>
    <%= f.collection_check_boxes( :inventory_item_ids, @inventory_items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @item.inventory_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
  </p>

  <p style="float:right">
    <%= f.submit "Edit Item" %>
  </p>
<% end %>

app/views/premade_items/edit_premade_inventory_item.html.erb
<%= link_to parent_view, premade_items_path, method: 'get', class: 'return-link' %>
<%= 'premade items' %>

<h3 style="text-align:center">
  <%= @premade_inventory_item.premade_item.name %>( <%= @premade_inventory_item.inventory_item.name %> )
</h3><br>

<%= simple_form_for @premade_inventory_item, url: update_premade_inventory_item_path( @premade_inventory_item ), method: 'put' do |f| %>

  <p>
    <%= f.label premade_inventory_item_unit_label_phrase_for( @premade_inventory_item ) %>
    
    <div class="input-group">
      <%= f.input :unit_count, label: false, input_html: { class: "form-control", placeholder: 'Quantity' } %>
      <%= f.input :unit, label: false, collection: @valid_units, input_html: { class: "form-control", placeholder: 'Unit' } %>
    </div>
  </p>
  
  <p style="float:right">
    <%= f.submit "Submit Changes" %>
  </p>
<% end %>

<%#= input the quantity of an inventory item for a premade item %>

app/views/premade_items/index.html.erb
<%= render 'table' %>

app/views/premade_items/new.html.erb
<%= link_to parent_view, premade_items_path, method: 'get', class: 'return-link' %>
<%= 'premade items' %>

<h3 style='text-align:center'>Add Premade Item</h3>

<%= simple_form_for @item do |f| %>
  <p>
    <%= f.label "Name*" %>
    <%= f.input :name, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Unit*" %>
    <%= link_to list_unicode, unit_chart_path, method: 'get' %>
    <div class="input-group">
      <%= f.input :item_quantity, label: false, input_html: { class: 'form-control', placeholder: 'quantity' } %>

      <span class="input-group-addon"> &nbsp &nbsp</span>
      
      <%= f.input :unit, as: :select, collection: @units, label: false, input_html: { class: 'form-control', placeholder: 'item unit' } %> 
    </div>
  </p>
  
  <p>
    <%= f.label 'Type*' %>
    <%= f.input :item_type, label: false, input_html: { type: 'text', list: 'types', autocomplete: 'off', class: 'form-control', value: 'Ingredient' } %>
    <datalist id="types">
      <% @types.each do | type | %>
        <option><%= type %></option>
      <% end %>
    </datalist>
  </p><br>
  
  <p>
    <%= f.label "Components:" %>
    <%= f.collection_check_boxes( :inventory_item_ids, @inventory_items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @item.inventory_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
  </p>

  <p style="float:right">
    <%= f.submit "Submit" %>
  </p>
<% end %>

<%# creates a premade_item with its composition( inventory_items ) %>

app/views/premade_items/show.html.erb
<%= link_to parent_view, premade_items_path, method: 'get', class: 'return-link' %>
<%= 'premade items' %>

<div class="container center">
  <div>
    <table class = 'table'>

      <caption id='sub-page-caption'>
        <h2>
          <%= link_to @premade_item.name, edit_premade_item_path( @premade_item ), class: compliance_class_of( @premade_item ), method: 'get' %>
        </h2>

        <h5 style="color: indigo">
          <%= unit_quantity_of( @premade_item ) + ': '%>
        </h5>

        <%= capacity_phrase_for( @premade_item ) %>
        <hr>
      </caption>
      
      <thead>
        <tr>
          <th>Item</th>
          
          <th>Quantity</th>
          
          <th>Cost</th>
        </tr>
      </thead>
      
      <% @premade_inventory_items.each do | join | %>
        <% item = join.inventory_item %>
      
        <tbody>
          <tr>
            <td>
              <%= link_to item.name, edit_premade_inventory_item_path( join ), class: compliance_class_of( join ), method: 'post' %>
            </td>
    
            <td>
              <%= join.unit_count %>
              <%= join.unit %>
            </td>
            
            <td>
              <%= item_cost( join ) %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

<% if @complete_item == 'true' %>
  <%= simple_form_for @premade_item do |f| %>
    <% verified = @premade_item.vouched %>
    
    <p>
      <%= f.hidden_field :vouched, value: verified ? false : true %>
    </p>

    <p style="float:right">
      <%= f.submit verified ? 'Deny' : 'Vouch' %>
    </p>
  <% end %>
<% end %>