config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  post 'users/user_branch/:id', to: 'users#user_branch', as: 'user_branch'
  put 'branch_products/update_branch_products_list/:id', to: 'branch_products#update_branch_products_list', as: 'branch_products_update'
  put 'branch_inventories/update_branch_inventory_items_list/:id', to: 'branch_inventories#update_branch_inventory_items_list', as: 'branch_inventory_update'
  put 'branch_premade_items/update_branch_premade_items_list/:id', to: 'branch_premade_items#update_branch_premade_items_list', as: 'branch_premade_items_update'
  
  # edit and update product's inventory item and premade item
  post 'products/edit_product_inventory_item/:id', to: 'products#edit_product_inventory_item', as: 'edit_product_item'
  put 'products/update_product_inventory_item/:id', to: 'products#update_product_inventory_item', as: 'update_product_item'
  post 'products/edit_product_premade_item/:id', to: 'products#edit_product_premade_item', as: 'edit_product_premade_item'
  put 'products/update_product_premade_item/:id', to: 'products#update_product_premade_item', as: 'update_product_premade_item'
  
  post 'premade_items/edit_premade_inventory_item/:id', to: 'premade_items#edit_premade_inventory_item', as: 'edit_premade_inventory_item'
  put 'premade_items/update_premade_inventory_item/:id', to: 'premade_items#update_premade_inventory_item', as: 'update_premade_inventory_item'

  post 'branch_inventories/edit_individual_branch_inventory_items', to: 'branch_inventories#edit_individual_branch_inventory_items', as: 'edit_individual_branch_inventory_items'
  put 'branch_inventories/update_individual_branch_inventory_items', to: 'branch_inventories#update_individual_branch_inventory_items', as: 'update_individual_branch_inventory_items'
  
  post 'branch_premade_items/edit_individual_branch_premade_items', to: 'branch_premade_items#edit_individual_branch_premade_items', as: 'edit_individual_branch_premade_items'
  put 'branch_premade_items/update_individual_branch_premade_items', to: 'branch_premade_items#update_individual_branch_premade_items', as: 'update_individual_branch_premade_items'
  
  get 'home/unit_chart', as: 'unit_chart'
  get 'transfers/selected_item_unit/:id', to: 'transfers#selected_item_unit'

  resources :products, :inventory_items, :premade_items, :transfers
  resources :branch_products, :branch_inventories, :branch_premade_items, only: [ :index, :edit, :update ]
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :branch_products, dependent: :destroy
  has_many :products, through: :branch_products

  has_many :branch_inventories, dependent: :destroy
  has_many :inventory_items, through: :branch_inventories

  has_many :branch_premade_items, dependent: :destroy
  has_many :premade_items, through: :branch_premade_items
  
  has_many :branch_users, dependent: :destroy
  has_many :users, through: :branch_users
end

app/models/branch_inventory.rb
class BranchInventory < ApplicationRecord
  validates_presence_of :stock, :margin, on: [ :update ]
  
  belongs_to :branch, optional: true
  belongs_to :inventory_item, optional: true
end

app/controllers/branch_inventories_controller.rb
class BranchInventoriesController < ApplicationController
  # store managers choose their branch's inventory items from the main lists of all inventory items
  
  def index
    @list = params[ :list ]
    @branch = current_user.branch
    @items = InventoryItem.all.order( :name )
    @branch_inventory_items = BranchInventory.where( branch_id: @branch.id )
  end

  def edit
    @branch_item = BranchInventory.find( params[ :id ] )
  end

  def update
    branch_item = BranchInventory.find( params[ :id ] )

    if branch_item.update( branch_item_params )
      redirect_to branch_inventories_path, notice: "#{ branch_item.inventory_item.name } updated"
    else
      redirect_back( fallback_location: root_path, notice: "update failed" )
    end
  end

  def update_branch_inventory_items_list
    branch = Branch.find( params[ :id ] )

    if branch.update( branch_item_params )
      redirect_to branch_inventories_path, notice: "#{ branch.name } inventory items updated"
    else
      redirect_to root_path, notice: "update failed"
    end
  end

  def edit_individual_branch_inventory_items
    @branch_inventories = BranchInventory.all
  end
  
  def update_individual_branch_inventory_items
    @branch_inventories = BranchInventory.update( params[ :branch_inventories ].keys, params[ :branch_inventories ].values).reject { |p| p.errors.empty? }
  
    if @branch_inventories.empty?
      flash[:notice] = "branch_inventories updated"
      
      redirect_to branch_inventories_path
    else
      render :action => "edit_individual_branch_inventory_items"
    end
  end

  private

  def branch_item_params
    params.require( :branch_inventory ).permit( :stock, :margin, inventory_item_ids: [] )
  end
end

app/helpers/branch_inventories_helper.rb
module BranchInventoriesHelper
end

app/views/branch_inventories/_fields.html.erb
<% bg = 'background-color:' + ( index.odd? ? 'darkgrey' : 'chocolate' ) %>

<div class="parent-container d-flex" style=<%= bg %>>
  <div class="container">
    <%= f.label item.name %>
  </div>

  <div class="container">
     <%= f.number_field :stock, step: :any %>
     <%= item.unit %>
  </div>
</div>

app/views/branch_inventories/_inventory_list.html.erb
<h3><%= @branch.name %> Inventory Items</h3>

<%= simple_form_for :branch_inventory, url: branch_inventory_update_path( @branch ), method:'put' do |f| %>
  <p>
    <%= f.collection_check_boxes( :inventory_item_ids, @items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @branch.inventory_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
  </p>

  <p style="float:right">
    <%= f.submit "Update Branch Inventory Items" %>
  </p>
<% end %><br><br>

app/views/branch_inventories/_inventory_table.html.erb
<%= render 'nav_tabs' %>

<table class = 'table'>
  
  <thead>
    <tr>
      <th>
        Items
        <%= link_to '[+]', branch_inventories_path( list: true ), method: 'get' %>
      </th>
      
      <th>
        Stock
        <%= link_to pen_edit_unicode, edit_individual_branch_inventory_items_path, method: 'post' %>
      </th>
    </tr>
  </thead>
  
  <% @branch_inventory_items.each do | join | %>
    <% item = InventoryItem.find( join.inventory_item_id ) %>
  
    <tbody>
      <tr>
        <td>
          <%= link_to item.name, edit_branch_inventory_path( join ), method: 'get' %>
        </td>

        <td>
          <%= inventory_stock_of( join, true ) %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/branch_inventories/_nav_tabs.html.erb
<ul class="nav nav-tabs">

  <li class="nav-item">
    <a class="nav-link active" href="#!">Market Items</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" href="<%= branch_premade_items_path %>" data-method = 'get' >Premade Items</a>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
       href="#" role="button" aria-haspopup="true" aria-expanded="false">
       Action
    </a>
    
    <div class="dropdown-menu">
      <div class="dropdown-item" id="trans-market-item" >Transfer</div>
      <a class="dropdown-item" href="#!">PullOut</a>
      <a class="dropdown-item" href="#!">Recieve</a>
    </div>
  </li>
  
  <%# pops out only when 'Transfer' action is clicked %>
  <li class="nav-item dropdown" id="trans-market-item-menu" hidden='true'>
    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
       href="#" role="button" aria-haspopup="true" aria-expanded="false">
       Transfer To
    </a>
    
    <div class="dropdown-menu">
      <% menu_branches = Branch.where.not( name: current_user.branch.name ) %>
      
      <% menu_branches.each do | branch | %>
        <a class="dropdown-item" href=<%= new_transfer_path( item_class: 'market items', branch_id: branch.id ) %> data-method = 'get'>
          <%= branch_name_of( branch ) %>
        </a>
      <% end %>
    </div>
  </li>
</ul>

<script>
  document.getElementById( "trans-market-item" ).addEventListener( 'click', function()  {
    document.getElementById( "trans-market-item-menu" ).hidden = false
  })
</script>

app/views/branch_inventories/edit.html.erb
<h3 style="text-align: center;">
  Edit <%= @branch_item.inventory_item.name %>
</h3>

<%= simple_form_for @branch_item do |f| %>
  <%= f.label 'Stock' %>
  <div class="input-group">
    <%= f.input :stock, label: false, input_html: { class: "form-control" } %>&nbsp
    
    <%= @branch_item.inventory_item.unit %>
  </div><br>
  
  <%= f.label 'Margin' %>
  <div class="input-group">
    <%= f.input :margin, label: false, input_html: { class: "form-control" } %>&nbsp

    <%= @branch_item.inventory_item.unit %>
  </div>

  <p style="float:right">
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/branch_inventories/edit_individual_branch_inventory_items.html.erb
<% index = 0 %>

<%= form_tag update_individual_branch_inventory_items_path, :method => :put do %>  
  <% for branch_inventory in @branch_inventories %>  
    <%= fields_for "branch_inventories[]", branch_inventory do |f| %>  
      
      <%= render "fields", f: f, index: index += 1, item: branch_inventory.inventory_item %>
    <% end %>  
  <% end %> <br>
  
  <p style="float:right">
    <%= submit_tag "Submit" %>
  </p>  
<% end %>  

app/views/branch_inventories/index.html.erb
<%= render @list.present? ? 'inventory_list' : 'inventory_table' %>