config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  post 'users/user_branch/:id', to: 'users#user_branch', as: 'user_branch'
  put 'branch_products/update_branch_products_list/:id', to: 'branch_products#update_branch_products_list', as: 'branch_products_update'
  put 'branch_inventories/update_branch_inventory_items_list/:id', to: 'branch_inventories#update_branch_inventory_items_list', as: 'branch_inventory_update'
  put 'branch_premade_items/update_branch_premade_items_list/:id', to: 'branch_premade_items#update_branch_premade_items_list', as: 'branch_premade_items_update'
  
  # edit and update product's inventory item and premade item
  post 'products/edit_product_inventory_item/:id', to: 'products#edit_product_inventory_item', as: 'edit_product_item'
  put 'products/update_product_inventory_item/:id', to: 'products#update_product_inventory_item', as: 'update_product_item'
  post 'products/edit_product_premade_item/:id', to: 'products#edit_product_premade_item', as: 'edit_product_premade_item'
  put 'products/update_product_premade_item/:id', to: 'products#update_product_premade_item', as: 'update_product_premade_item'
  
  post 'premade_items/edit_premade_inventory_item/:id', to: 'premade_items#edit_premade_inventory_item', as: 'edit_premade_inventory_item'
  put 'premade_items/update_premade_inventory_item/:id', to: 'premade_items#update_premade_inventory_item', as: 'update_premade_inventory_item'

  post 'branch_inventories/edit_individual_branch_inventory_items', to: 'branch_inventories#edit_individual_branch_inventory_items', as: 'edit_individual_branch_inventory_items'
  put 'branch_inventories/update_individual_branch_inventory_items', to: 'branch_inventories#update_individual_branch_inventory_items', as: 'update_individual_branch_inventory_items'
  
  post 'branch_premade_items/edit_individual_branch_premade_items', to: 'branch_premade_items#edit_individual_branch_premade_items', as: 'edit_individual_branch_premade_items'
  put 'branch_premade_items/update_individual_branch_premade_items', to: 'branch_premade_items#update_individual_branch_premade_items', as: 'update_individual_branch_premade_items'
  
  get 'home/unit_chart', as: 'unit_chart'
  get 'transfers/selected_item_unit/:id', to: 'transfers#selected_item_unit'

  resources :products, :inventory_items, :premade_items, :transfers
  resources :branch_products, :branch_inventories, :branch_premade_items, only: [ :index, :edit, :update ]
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :price, on: [ :create, :update ]
  validates_uniqueness_of :name, on: [ :create, :update ]
  
  has_many :branch_products, dependent: :destroy
  has_many :branches, through: :branch_products

  has_many :product_inventory_items, dependent: :destroy
  has_many :inventory_items, through: :product_inventory_items
  
  has_many :product_premade_items, dependent: :destroy
  has_many :premade_items, through: :product_premade_items

  before_validation do | product |
    product.name = product.name.downcase.capitalize
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @items = InventoryItem.all
    @premade_items = PremadeItem.all
  end

  def create
    product = Product.new( product_params )

    if product.save
      redirect_back( fallback_location: products_path, notice: "#{ product.name } has been successfully added" )
    else
      redirect_back( fallback_location: products_path, notice: 'failed to save new product' )
    end
  end

  def edit
    @product = Product.find( params[ :id ] )
    @premade_items = PremadeItem.all
    @items = InventoryItem.all
  end

  def update
    product = Product.find( params[ :id ] )

    if product.update( product_params )
      redirect_to product_path( product ), method: 'get', notice: "edit successful"
    else
      redirect_back( fallback_location: products_path, notice: 'edit failed' )
    end
  end

  def show
    @product = Product.find( params[ :id ] )
    
    inventory_items = ProductInventoryItem.where( product_id: @product.id )
    premade_items = ProductPremadeItem.where( product_id: @product.id )
    @product_items = premade_items + inventory_items

    @complete_item = params[ :complete_item ]
  end

  def destroy
    product = Product.find( params[ :id ] )

    if product.destroy
      redirect_to products_path, method: 'get', notice: "#{ product.name } has been deleted"
    else
      redirect_back( fallback_location: products_path, notice: 'delete failed' )
    end
  end

  def edit_product_inventory_item
    @product_item = ProductInventoryItem.find( params[ :id ] )
    
    @valid_units = helpers.find_valid_item_units( @product_item )
  end
  
  def update_product_inventory_item
    product_item = ProductInventoryItem.find( params[ :id ] )

    if product_item.update( product_item_params )
      redirect_to product_path( product_item.product, focus: true ), method: 'get', notice: 'edit successful'
    else
      redirect_to products_path, method: 'get', notice: "edit failed"
    end
  end
  
  def edit_product_premade_item
    @product_premade_item = ProductPremadeItem.find( params[ :id ] )
    
    @valid_units = helpers.find_valid_item_units( @product_premade_item )
  end
  
  def update_product_premade_item
    product_item = ProductPremadeItem.find( params[ :id ] )

    if product_item.update( product_premade_params )
      redirect_to product_path( product_item.product, focus: true ), method: 'get', notice: 'edit successful'
    else
      redirect_to products_path, method: 'get', notice: "edit failed"
    end
  end

  private

  def product_params
    params.require( :product ).permit( :name, :price, :min_net, :add_on, :vouched, inventory_item_ids: [], premade_item_ids: [] )
  end
  
  def product_item_params
    params.require( :product_inventory_item ).permit( :unit, :unit_count )
  end
  
  def product_premade_params
    params.require( :product_premade_item ).permit( :unit, :unit_count )
  end
end

app/helpers/costings/product.rb
module Costings::Product
  
  def product_price( product )
    return nil unless verified_and_complete?( product )
    
    product.price
  end
  
  def product_cost( product )
    return nil unless verified_and_complete?( product )
    
    product_inventory_items = ProductInventoryItem.where( product: product )
    product_premade_items = ProductPremadeItem.where( product: product )

    product_items = product_inventory_items + product_premade_items

    product_items.inject( 0 ) { | sum, item | sum + cost_of( item ) }
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def item_of( join_model )
    case join_model.class.name
    when 'ProductInventoryItem'
      join_model.inventory_item
    when 'ProductPremadeItem'
      join_model.premade_item
    end
  end
end

app/helpers/validators/product.rb
module Validators::Product 
    
  def product_has_no?( *components )
    components = components.inject( 0 ) { | sum , c | sum + c.count }
  
    components.zero?
  end

  def invalid?( product_premade_items )
    return false if product_premade_items.nil? # product w/out premade_items is valid
    
    product_premade_items.each do | joint |
      if joint.unit_count.nil? || !verified_and_complete?( joint.premade_item )
        return true
        
        break
      end
    end

    false
  end
  
  def complete_product_data_values?( product )
    product_items = ProductInventoryItem.where( product: product )
    product_premade_items = ProductPremadeItem.where( product: product )

    return false if invalid?( product_premade_items ) ||
                    null_data_is_detected_from?( product_items ) ||
                    product_has_no?( product_items, product_premade_items )
 
    true
  end
end

app/views/products/_table.html.erb
<table class = 'table'>

  <caption id='caption'>
    Products
    <hr>
  </caption>
  
  <thead>
    <tr>
      <th>
        Product
        <%= link_to '[ ' "\u{ 002B }" ' ]'.encode( 'utf-8' ), new_product_path, method: 'get' %>
      </th>
      
      <th>Price</th>
      
      <th>Cost</th>
      
      <th>Net</th>
    </tr>
  </thead>
  
  <%# list of all products %>
  <% @products.each do | product | %>
    
    <tbody>
      <tr>
        <td>
          <%= link_to product.name, product_path( product, complete_item: complete_product_data_values?( product ) ), class: compliance_class_of( product ), method: 'get' %>
        </td>

        <td>
          <%= price_of( product ) %>
        </td>

        <td>
          <%= cost_of( product ) %>
        </td>
        
        <td>
          <%= net_of( product ) %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/products/edit.html.erb
<%= link_to parent_view, products_path, method: 'get', class: 'return-link' %>
<%= 'products' %>

<h3 style="text-align: center;">
  Product(
  <%= @product.name %>
  )
  <%= link_to '[x]', product_path( @product ), method: 'delete', data: { confirm: 'Are you sure you want to delete this ingredient?' } %>
</h3>

<%= simple_form_for @product do | f | %>

  <div style="float: right">
    <%= f.input :add_on, inline_label: true %>
  </div><br>
  
  <p>
    <%= f.label "Name*" %>
    <%= f.input :name, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Price*" %>
    <%= f.input :price, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Minimum Net" %>
    <%= f.input :min_net, label: false, input_html: { class: "form-control" } %>
  </p>

  <p>
    <%= f.label 'Components:' %>
    <%= f.collection_check_boxes( :premade_item_ids, @premade_items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @product.premade_items.pluck( :name ).include?( item.object.name ), disabled: verified_and_complete?( PremadeItem.find( item.object.id ) ) ? false : true ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
    
    <%= f.collection_check_boxes( :inventory_item_ids, @items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @product.inventory_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
  </p>

  <p style="float: right">
    <%= f.label 'Vouch' %>
    <%= f.check_box :vouched %>
    
    &nbsp&nbsp&nbsp&nbsp
    
    <%= f.submit "Update Product" %>
  </p>
<% end %><br><br>

app/views/products/edit_product_inventory_item.html.erb
<%= link_to parent_view, products_path, method: 'get', class: 'return-link' %>
<%= 'products' %>

<h3 style="text-align:center"><%= @product_item.product.name %>( <%= @product_item.inventory_item.name %> )</h3><br>

<%= simple_form_for @product_item, url: update_product_item_path( @product_item ), method: 'put' do |f| %>

  <p>
    <%= f.label edit_product_unit_label_phrase_for( @product_item, @product_item.inventory_item ) %>
    
    <div class="input-group">
      <%= f.input :unit_count, label: false, input_html: { class: "form-control", placeholder: 'Quantity' } %>
      <%= f.input :unit, label: false, collection: @valid_units, input_html: { class: "form-control", placeholder: 'Unit' } %>
    </div>
  </p>
  
  <p style="float:right">
    <%= f.submit "Submit Changes" %>
  </p>
<% end %>

<%# input the amount of inventory item needed for a product or a sub-product %>

app/views/products/edit_product_premade_item.html.erb
<%= link_to parent_view, products_path, method: 'get', class: 'return-link' %>
<%= 'products' %>

<h3 style="text-align:center">
  <%= @product_premade_item.product.name %>( <%= @product_premade_item.premade_item.name %> )
</h3><br>

<%= simple_form_for @product_premade_item, url: update_product_premade_item_path( @product_premade_item ), method: 'put' do |f| %>

  <p>
    <%= f.label edit_product_unit_label_phrase_for( @product_premade_item, @product_premade_item.premade_item ) %>
    
    <div class="input-group">
      <%= f.input :unit_count, label: false, input_html: { class: "form-control", placeholder: 'Quantity' } %>
      <%= f.input :unit, label: false, collection: @valid_units, input_html: { class: "form-control", placeholder: 'Unit' } %>
    </div>
  </p>
  
  <p style="float:right">
    <%= f.submit "Submit Changes" %>
  </p>
<% end %><br>

<% unless verified_and_complete?( @product_premade_item.premade_item ) %>
  <p style="color:red; font-style: italic;">
    *
    <%= @product_premade_item.product.name %>
    's premade item
    ' <%= @product_premade_item.premade_item.name %> '
    has insufficent data; please review and edit through this
    <%= link_to 'link', premade_item_path( @product_premade_item.premade_item, complete_item: complete_premade_item_data_values?( @product_premade_item.premade_item ) ), method: 'get' %>
  </p>
<% end %>


<%#= 'input the amount of premade item needed for a product' %>

app/views/products/index.html.erb
<%= render 'table' %>

app/views/products/new.html.erb
<%= link_to parent_view, products_path, method: 'get', class: 'return-link' %>
<%= 'products' %>

<h3 style='text-align:center'>Add Product</h3>

<%= simple_form_for @product do |f| %>
  <div style="float: right">
    <%= f.input :add_on, inline_label: true %>
  </div><br>
  
  <p>
    <%= f.label "Name*" %>
    <%= f.input :name, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Price*" %>
    <%= f.input :price, label: false, input_html: { class: "form-control" } %>
  </p>
  
  <p>
    <%= f.label "Minimum Net" %>
    <%= f.input :min_net, label: false, input_html: { class: "form-control" } %>
  </p><br>

  <p>
    <%= f.label "Components:" %>

    <%= f.collection_check_boxes( :premade_item_ids, @premade_items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @product.premade_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
    
    <%= f.collection_check_boxes( :inventory_item_ids, @items, :id, :name, :item_wrapper_class => 'checkbox_container' ) do | item | %>
      <div class="form-check">
        <%= item.check_box( class: "form-check-input", checked: @product.inventory_items.pluck( :name ).include?( item.object.name ) ) %>
        <%= item.label( class: "form-check-label" ) %>
      </div>
    <% end %>
  </p>

  <p style="float: right">
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/products/show.html.erb
<%= link_to parent_view, products_path, method: 'get', class: 'return-link' %>
<%= 'products' %>

<div class="container center">
  <div>
    <table class = 'table'>

      <caption id='sub-page-caption'>
        <h2>
          <%= link_to @product.name, edit_product_path( @product ), method: 'get', class: compliance_class_of( @product ) %>
        </h2>
        
        <hr>
      </caption>
      
      <thead>
        <tr>
          <th>Item</th>
          
          <th>Amount</th>
          
          <th>Cost</th>
        </tr>
      </thead>
      
      <%# list of product components( product_premade_item && product_inventory_item ) %>
      <% @product_items.each do | join | %>
        <% item = item_of( join ) %>
        <% item_class = item.class.name %>
        
        <tbody>
          <tr>
            <td>
              <% case item_class %>
              <% when 'InventoryItem' %>
                <%= link_to item.name, edit_product_item_path( join ), method: 'post', class: compliance_class_of( join ) %>
              <% when 'PremadeItem' %>
                <%= link_to item.name, edit_product_premade_item_path( join ), method: 'post', class: compliance_class_of( join ) %>
              <% end %>
            </td>
    
            <td>
              <%= join.unit_count %>
              <%= join.unit %>
            </td>
            
            <td>
              <%= cost_of( join ) %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>
    
<% if @complete_item == 'true' %>
  <%= simple_form_for @product do |f| %>
    <% verified = @product.vouched %>
    
    <p>
      <%= f.hidden_field :vouched, value: verified ? false : true %>
    </p>

    <p style="float:right">
      <%= f.submit verified ? 'Deny' : 'Vouch' %>
    </p>
  <% end %>
<% end %>